project_id = "yjjxsirrirpnrzrxpjvj"

[functions.google-calendar-auth]
verify_jwt = true


[functions.unpublish-schedule]
verify_jwt = true

[functions.send-schedule-email]
verify_jwt = true


[functions.generate-ai-schedule]
verify_jwt = true
