// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjjxsirrirpnrzrxpjvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqanhzaXJyaXJwbnJ6cnhwanZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDkxNTQsImV4cCI6MjA3MjMyNTE1NH0.1GLxz5Q9qx47l6aL8048nLk3gOLFpBJUxjy7GeQ6GyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});